version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.15.3
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
    restart: always

  traefik:
    image: traefik:v3.3.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.endpoint.address=consul:8500"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - consul
    restart: always

  keycloakdb:
    image: postgres:latest
    container_name: keycloakdb
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=cemal
      - KEYCLOAK_ADMIN_PASSWORD=123456789
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloakdb:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KEYCLOAK_HTTP_ENABLED=true
      - KEYCLOAK_HOSTNAME=localhost
    ports:
      - "8081:8080"
    command:
      - start-dev
    depends_on:
      - consul
      - keycloakdb
    restart: always

